### ISSUE TITLE
USER STORY Logout

### ISSUE THREAD

**Issue by frirsta** [frirsta/fullstack#8]
As a **Site Admin** I can **logout** so that **someone else using my computer cant post from my account**

## Acceptance Criteria
* Acceptance Criteria 1: User can click 'Logout'
* Acceptance Criteria 2:
* Acceptance Criteria 3:

## Tasks
- [ ] Task 1: add logout url to urls.py
- [ ] Task 2: create logout function
- [ ] Task 3: import logout function to views.py
